language: c
cache: false
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - avsm
    packages:
      - check
      - libcv-dev             # For av_test.
      - libhighgui-dev        # For av_test.
      - libopencv-contrib-dev # For av_test.
      - libsndfile1-dev       # For av_test.
      - libvpx-dev
      - opam                  # For apidsl and Frama-C.
      - portaudio19-dev       # For av_test.
      - texinfo               # For libconfig.

script:
    - sudo apt-get update
    - sudo apt-get install cmake
    - aptitude search 4l|grep -i convert ; echo exit 0
    - aptitude search 4l|grep -i v4l ; echo exit 0
    - sudo apt-get install build-essential libtool autotools-dev automake checkinstall check git yasm
    - sudo apt-get install libv4lconvert0
    - sudo apt-get install libv4l-dev
    - sudo apt-get install libjpeg-dev
    - sudo apt-get install libvpx-dev
    - sudo apt-get install pkg-config
    - sudo apt-get install linux-generic
    - sudo bash -c "echo '::1             localhost ipv6-localhost ipv6-loopback' >> /etc/hosts" # ipv6 localhost entry

    - gcc --version ; echo exit 0
    - clang --version ; echo exit 0

    ### submodules ----------------
    - git submodule add --force https://github.com/TokTok/c-toxcore c-toxcore ; echo ok
    - git submodule add --force https://github.com/jedisct1/libsodium libsodium ; echo ok
    - git submodule init ; git submodule update ; echo ok
    - cd c-toxcore/ ; git checkout a096c71db867ac83fc3e01e0fbe98573d20f9286
    - cd ..
    - cd libsodium/ ; git checkout tags/1.0.11
    - cd ..
    ### submodules ----------------

    ### ------- compile and install libsodium -------
    - cd libsodium/ ; ./autogen.sh
    - ./configure && make check
    - sudo bash -c "printf 'y\naa\n\n' | checkinstall --install --pkgname libsodium --pkgversion 1.0.11 --nodoc --deldesc=no --pkglicense='GPL2'"
    - sudo ldconfig
    - sudo ldconfig -v 2>/dev/null | grep sodium
    - cd ..
    ### ------- compile and install libsodium -------

    ### ------- compile and install libopus -------
    - wget http://downloads.xiph.org/releases/opus/opus-1.1.3.tar.gz -O opus.tgz
    - tar -xzvf opus.tgz
    - rm opus.tgz
    - ls -al
    - mv -v opus* libopus
    - cd libopus/ # autogen ?
    - ./configure && make check
    - sudo bash -c "printf 'y\naa\n\n' | checkinstall --install --pkgname libopus --pkgversion 1.1.3 --nodoc --deldesc=no --pkglicense='GPL2'"
    - sudo ldconfig
    - sudo ldconfig -v 2>/dev/null | grep opus
    - cd ..
    ### ------- compile and install libopus -------

    ### ------------ compile and install c-toxcore ------------
    - cd c-toxcore ; cmake -DWARNINGS=OFF .
    - make
    #- sudo make install
    - sudo bash -c "printf 'y\naa\n\n' | checkinstall --install --pkgname toxcore --pkgversion 0.1.2 --nodoc --deldesc=no --pkglicense='GPL2'"
    - sudo ldconfig -v 2>/dev/null | grep toxcore
    ### ------------ run tests
    #- make test ARGS="-V" ; ex1=$? ; if [ $ex1 -ne 0 ]; then sleep 60; make test ARGS="-V" ; exit $? ; fi
    - cd ..
    ### ------------ compile and install c-toxcore ------------

    - cd toxdoorspy ; gcc -O2 -fPIC -Wall -Wextra -o toxdoorspy toxdoorspy.c -std=gnu99 -lsodium -I/usr/local/include/ -ltoxcore -ltoxav -lpthread -lvpx -lv4lconvert
    - ldd toxdoorspy ; echo exit 0
    - find / -name '*libjpeg*' 2> /dev/null ; echo exit 0
    - gcc -O2 -Wall -Wextra -o toxdoorspy_static toxdoorspy.c -static -std=gnu99 -L/usr/local/lib -I/usr/local/include/ -lsodium -ltoxcore -ltoxav -ltoxgroup -ltoxmessenger -ltoxfriends -ltoxnetcrypto -ltoxdht -ltoxnetwork -ltoxcrypto -lsodium -lpthread -static-libgcc -static-libstdc++ -lopus -lvpx -lm -lpthread -lv4lconvert -ljpeg -lm -lrt
    - ls -al toxdoorspy toxdoorspy_static

